import type { Context, MiddlewareHandler } from "hono";
import { connect, type Sql } from "../db";
import type { Env } from "../env";
import { HttpError } from "../http";
import { decode, TokenError } from "./jwt";
import { background } from "../runtime";

export interface User {
  id: number;
  password: string;
  is_active: boolean;
  username: string | null;
  email: string;
  full_name: string;
  role: string;
  profile_completed: boolean;
  matric_number: string;
  faculty: string;
  department: string;
  level: string;
  semester: string;
  institution: string;
  current_courses: unknown;
  academic_goal: unknown;
  weak_courses: unknown;
  preferred_learning_style: string;
  preferred_resource_types: unknown;
  study_hours_per_week: number | null;
  exam_preparation_focus: string;
  career_interest: string;
  avatar: string;
  date_joined: Date;
  google_id: string;
  supabase_user_id: string;
  is_google_account: boolean;
  sui_address: string | null;
}

export type AppEnv = { Bindings: Env; Variables: { sql: Sql; user: User } };
export type Ctx = Context<AppEnv>;

/** UserSerializer. first_name is derived, like the Django SerializerMethodField. */
export function serializeUser(user: User) {
  const firstName = user.full_name
    ? user.full_name.trim().split(/\s+/)[0]
    : user.email
      ? user.email.split("@")[0]
      : "Student";
  return {
    id: user.id,
    full_name: user.full_name,
    first_name: firstName,
    username: user.username,
    email: user.email,
    role: user.role,
    profile_completed: user.profile_completed,
    matric_number: user.matric_number,
    faculty: user.faculty,
    department: user.department,
    level: user.level,
    semester: user.semester,
    institution: user.institution,
    current_courses: user.current_courses,
    academic_goal: user.academic_goal,
    weak_courses: user.weak_courses,
    preferred_learning_style: user.preferred_learning_style,
    preferred_resource_types: user.preferred_resource_types,
    study_hours_per_week: user.study_hours_per_week,
    exam_preparation_focus: user.exam_preparation_focus,
    career_interest: user.career_interest,
    avatar: user.avatar,
    date_joined: user.date_joined,
  };
}

export async function userById(sql: Sql, id: number): Promise<User | null> {
  const [row] = await sql`select * from accounts_user where id = ${id}`;
  return (row as unknown as User) ?? null;
}

export async function userByEmail(sql: Sql, email: string): Promise<User | null> {
  const [row] = await sql`select * from accounts_user where lower(email) = lower(${email}) limit 1`;
  return (row as unknown as User) ?? null;
}

/**
 * create_user: every NOT NULL column filled, because the schema was generated by
 * Django, which applies defaults in Python rather than in the database.
 */
export async function createUser(
  sql: Sql,
  fields: Partial<User> & { email: string; password: string; full_name: string },
): Promise<User> {
  const now = new Date();
  const row = {
    password: fields.password,
    last_login: null,
    is_superuser: false,
    first_name: "",
    last_name: "",
    is_staff: false,
    is_active: true,
    date_joined: now,
    // Absent means NULL: several empty strings would collide under the unique index.
    username: fields.username || null,
    email: fields.email.toLowerCase(),
    full_name: fields.full_name,
    role: fields.role || "student",
    department: "",
    level: "",
    institution: "",
    avatar: fields.avatar || "",
    google_id: fields.google_id || "",
    is_google_account: fields.is_google_account || false,
    created_at: now,
    updated_at: now,
    supabase_user_id: fields.supabase_user_id || "",
    academic_goal: sql.json([] as never),
    career_interest: "",
    current_courses: sql.json([] as never),
    exam_preparation_focus: "",
    faculty: "",
    matric_number: "",
    preferred_learning_style: "",
    preferred_resource_types: sql.json([] as never),
    profile_completed: false,
    semester: "",
    study_hours_per_week: null,
    weak_courses: sql.json([] as never),
    sui_address: fields.sui_address || null,
  };
  const [created] = await sql`insert into accounts_user ${sql(row as never)} returning *`;
  return created as unknown as User;
}

/** Django's set_unusable_password(): "!" plus 40 random characters. */
export function unusablePassword(): string {
  const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  const bytes = crypto.getRandomValues(new Uint8Array(40));
  return "!" + Array.from(bytes, (b) => alphabet[b % alphabet.length]).join("");
}

/** Opens the per-request database connection and closes it after the response. */
export const database: MiddlewareHandler<AppEnv> = async (c, next) => {
  const sql = connect(c.env);
  c.set("sql", sql);
  try {
    await next();
  } finally {
    await background(c as never, sql.end({ timeout: 2 }).catch(() => undefined));
  }
};

/** JWTAuthentication + IsAuthenticated, with DRF's error bodies. */
export const requireUser: MiddlewareHandler<AppEnv> = async (c, next) => {
  const header = c.req.header("Authorization") || "";
  const [scheme, token] = header.split(" ");
  if (scheme !== "Bearer" || !token) {
    throw new HttpError(401, { detail: "Authentication credentials were not provided." });
  }
  let payload;
  try {
    payload = await decode(token, c.env.SECRET_KEY, "access");
  } catch (error) {
    throw new HttpError(401, {
      detail: "Given token not valid for any token type",
      code: "token_not_valid",
      messages: [{ token_class: "AccessToken", token_type: "access", message: error instanceof TokenError ? error.message : "Token is invalid" }],
    });
  }
  const user = await userById(c.get("sql"), Number(payload.user_id));
  if (!user) throw new HttpError(401, { detail: "User not found", code: "user_not_found" });
  if (!user.is_active) throw new HttpError(401, { detail: "User is inactive", code: "user_inactive" });
  c.set("user", user);
  await next();
};

export const requireAdmin: MiddlewareHandler<AppEnv> = async (c, next) => {
  if (c.get("user")?.role !== "admin") throw new HttpError(403, { detail: "Admin role is required." });
  await next();
};
