# Generated by Django 5.2.14 on 2026-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
