# Generated by Django 6.0.5 on 2026-08-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_academic_goal_user_career_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiLoginChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='sui_address',
            field=models.CharField(blank=True, db_index=True, max_length=66, null=True, unique=True),
        ),
    ]
