# Generated by Django 5.2.14 on 2026-05-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='focused_end_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='focused_extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='focused_start_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='total_page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
