# Generated by Django 6.0.5 on 2026-08-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_enable_rls_all_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersessionactivity',
            name='memory_written',
            field=models.BooleanField(default=False),
        ),
    ]
