// Assemble the YouTube study document as a .docx in the browser. A port of
// apps/youtube_docx/docx_builder.py: same sections, order, sizes and colours.
// The Worker returns the structured content as JSON; building the file here
// keeps that request inside the free Cloudflare plan's CPU budget.

import { cleanExtractedText } from "@shared/text";

const BRAND_BLUE = "1D4ED8";
const INK = "0F172A";
const MUTED = "475569";

// docx measures font size in half-points and spacing in twentieths of a point.
const pt = (value) => value * 2;
const spacing = (value) => value * 20;

const asText = (value) => cleanExtractedText(String(value ?? "")).trim();
const asList = (value) =>
  Array.isArray(value) ? value.map(asText).filter(Boolean) : asText(value) ? [asText(value)] : [];

export async function buildStudyDocx(content, metadata, source = "captions") {
  const { AlignmentType, Document, Packer, Paragraph, TextRun } = await import("docx");
  content = content || {};
  const children = [];

  const run = (text, { size = 11, color = INK, bold = false } = {}) =>
    new TextRun({ text, size: pt(size), color, bold, font: "Calibri" });

  const heading = (text, size = 15, color = BRAND_BLUE, before = 14) => {
    if (!text) return;
    children.push(
      new Paragraph({
        spacing: { before: spacing(before), after: spacing(4) },
        children: [run(text, { size, color, bold: true })]
      })
    );
  };
  const body = (text, color = INK, size = 11) => {
    if (!text) return;
    children.push(new Paragraph({ spacing: { after: spacing(6) }, children: [run(text, { size, color })] }));
  };
  const bullet = (runs) => children.push(new Paragraph({ bullet: { level: 0 }, children: runs }));
  const bullets = (items, color = INK, size = 11) => items.forEach((item) => bullet([run(item, { size, color })]));
  const pairs = (items, first, second) =>
    (Array.isArray(items) ? items : [])
      .filter((item) => item && typeof item === "object" && asText(item[first]))
      .map((item) => [asText(item[first]), asText(item[second])]);

  // Title block
  const title = asText(content.title) || asText(metadata?.title) || "Study Document";
  children.push(new Paragraph({ alignment: AlignmentType.LEFT, children: [run(title, { size: 22, bold: true })] }));
  const meta = [];
  if (asText(metadata?.channel)) meta.push(`Channel: ${asText(metadata.channel)}`);
  meta.push("Generated by StudyPilot");
  if (source) meta.push(`Source: ${source}`);
  children.push(new Paragraph({ children: [run(meta.join("  •  "), { size: 9, color: MUTED })] }));

  const intro = asText(content.introduction);
  if (intro) {
    heading("Introduction");
    body(intro);
  }

  const objectives = asList(content.learning_objectives);
  if (objectives.length) {
    heading("Learning Objectives");
    bullets(objectives);
  }

  const sections = Array.isArray(content.sections) ? content.sections : [];
  if (sections.length) {
    heading("Lecture Notes", 16);
    for (const section of sections) {
      if (!section || typeof section !== "object") continue;
      heading(asText(section.heading), 13, BRAND_BLUE, 10);
      body(asText(section.summary));
      const keyPoints = asList(section.key_points);
      if (keyPoints.length) {
        body("Key points:", MUTED, 10);
        bullets(keyPoints);
      }
      const examples = asList(section.examples);
      if (examples.length) {
        body("Examples:", MUTED, 10);
        bullets(examples);
      }
    }
  }

  const concepts = pairs(content.key_concepts, "term", "definition");
  if (concepts.length) {
    heading("Key Concepts");
    concepts.forEach(([term, definition]) => bullet([run(`${term}: `, { bold: true }), run(definition)]));
  }

  const takeaways = asList(content.important_takeaways);
  if (takeaways.length) {
    heading("Important Takeaways");
    bullets(takeaways);
  }

  const summary = asText(content.summary);
  if (summary) {
    heading("Summary");
    body(summary);
  }

  const revision = pairs(content.revision_questions, "question", "answer");
  if (revision.length) {
    heading("Revision Questions");
    revision.forEach(([question, answer], index) => {
      children.push(new Paragraph({ children: [run(`${index + 1}. ${question}`, { bold: true })] }));
      if (answer) body(`Answer: ${answer}`, MUTED, 10);
    });
  }

  const mcqs = (Array.isArray(content.mcqs) ? content.mcqs : []).filter((item) => item && typeof item === "object" && asText(item.question));
  if (mcqs.length) {
    heading("Practice MCQs");
    mcqs.forEach((item, index) => {
      children.push(new Paragraph({ children: [run(`${index + 1}. ${asText(item.question)}`, { bold: true })] }));
      bullets(asList(item.options), INK, 10);
      const answer = asText(item.correct_answer);
      if (answer) body(`Correct answer: ${answer}`, BRAND_BLUE, 10);
      const explanation = asText(item.explanation);
      if (explanation) body(`Why: ${explanation}`, MUTED, 10);
    });
  }

  const glossary = pairs(content.glossary, "term", "meaning");
  if (glossary.length) {
    heading("Glossary");
    glossary.forEach(([term, meaning]) => bullet([run(`${term}: `, { bold: true }), run(meaning)]));
  }

  const checklist = asList(content.study_checklist);
  if (checklist.length) {
    heading("Study Checklist");
    checklist.forEach((item) => children.push(new Paragraph({ children: [run(`☐  ${item}`)] })));
  }

  const document = new Document({
    styles: { default: { document: { run: { font: "Calibri", size: pt(11) } } } },
    sections: [{ children }]
  });
  return Packer.toBlob(document);
}
