"""Build a clean, well-structured .docx study document from AI JSON content."""

import io

from docx import Document as DocxDocument
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

from apps.documents.services import clean_extracted_text

BRAND_BLUE = RGBColor(0x1D, 0x4E, 0xD8)
INK = RGBColor(0x0F, 0x17, 0x2A)
MUTED = RGBColor(0x47, 0x55, 0x69)


def _as_text(value):
    return clean_extracted_text(str(value or "")).strip()


def _as_list(value):
    if isinstance(value, list):
        return [_as_text(item) for item in value if _as_text(item)]
    text = _as_text(value)
    return [text] if text else []


def _heading(document, text, size=15, color=BRAND_BLUE, space_before=14):
    if not text:
        return
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_before = Pt(space_before)
    paragraph.paragraph_format.space_after = Pt(4)
    run = paragraph.add_run(text)
    run.bold = True
    run.font.size = Pt(size)
    run.font.color.rgb = color


def _body(document, text, color=INK, size=11):
    if not text:
        return
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.space_after = Pt(6)
    run = paragraph.add_run(text)
    run.font.size = Pt(size)
    run.font.color.rgb = color


def _bullets(document, items, color=INK):
    for item in items:
        paragraph = document.add_paragraph(style="List Bullet")
        run = paragraph.add_run(item)
        run.font.size = Pt(11)
        run.font.color.rgb = color


def build_study_docx(content, metadata, source="captions"):
    """content: dict from the AI generator. Returns BytesIO of the .docx file."""
    content = content or {}
    document = DocxDocument()

    normal = document.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)

    # Title block
    title = _as_text(content.get("title")) or _as_text(metadata.get("title")) or "Study Document"
    title_paragraph = document.add_paragraph()
    title_paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT
    title_run = title_paragraph.add_run(title)
    title_run.bold = True
    title_run.font.size = Pt(22)
    title_run.font.color.rgb = INK

    meta_bits = []
    if _as_text(metadata.get("channel")):
        meta_bits.append(f"Channel: {_as_text(metadata.get('channel'))}")
    meta_bits.append("Generated by StudyPilot")
    if source:
        meta_bits.append(f"Source: {source}")
    meta_paragraph = document.add_paragraph()
    meta_run = meta_paragraph.add_run("  •  ".join(meta_bits))
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = MUTED

    # Introduction
    intro = _as_text(content.get("introduction"))
    if intro:
        _heading(document, "Introduction")
        _body(document, intro)

    # Learning objectives
    objectives = _as_list(content.get("learning_objectives"))
    if objectives:
        _heading(document, "Learning Objectives")
        _bullets(document, objectives)

    # Sections
    sections = content.get("sections") or []
    if isinstance(sections, list) and sections:
        _heading(document, "Lecture Notes", size=16)
        for section in sections:
            if not isinstance(section, dict):
                continue
            _heading(document, _as_text(section.get("heading")), size=13, space_before=10)
            _body(document, _as_text(section.get("summary")))
            key_points = _as_list(section.get("key_points"))
            if key_points:
                _body(document, "Key points:", color=MUTED, size=10)
                _bullets(document, key_points)
            examples = _as_list(section.get("examples"))
            if examples:
                _body(document, "Examples:", color=MUTED, size=10)
                _bullets(document, examples)

    # Key concepts
    concepts = content.get("key_concepts") or []
    concept_pairs = [
        (_as_text(item.get("term")), _as_text(item.get("definition")))
        for item in concepts
        if isinstance(item, dict) and _as_text(item.get("term"))
    ]
    if concept_pairs:
        _heading(document, "Key Concepts")
        for term, definition in concept_pairs:
            paragraph = document.add_paragraph(style="List Bullet")
            term_run = paragraph.add_run(f"{term}: ")
            term_run.bold = True
            term_run.font.size = Pt(11)
            term_run.font.color.rgb = INK
            def_run = paragraph.add_run(definition)
            def_run.font.size = Pt(11)
            def_run.font.color.rgb = INK

    # Important takeaways
    takeaways = _as_list(content.get("important_takeaways"))
    if takeaways:
        _heading(document, "Important Takeaways")
        _bullets(document, takeaways)

    # Summary
    summary = _as_text(content.get("summary"))
    if summary:
        _heading(document, "Summary")
        _body(document, summary)

    # Revision questions
    revision = content.get("revision_questions") or []
    revision_pairs = [
        (_as_text(item.get("question")), _as_text(item.get("answer")))
        for item in revision
        if isinstance(item, dict) and _as_text(item.get("question"))
    ]
    if revision_pairs:
        _heading(document, "Revision Questions")
        for index, (question, answer) in enumerate(revision_pairs, 1):
            q_paragraph = document.add_paragraph()
            q_run = q_paragraph.add_run(f"{index}. {question}")
            q_run.bold = True
            q_run.font.size = Pt(11)
            q_run.font.color.rgb = INK
            if answer:
                _body(document, f"Answer: {answer}", color=MUTED, size=10)

    # MCQs
    mcqs = content.get("mcqs") or []
    valid_mcqs = [item for item in mcqs if isinstance(item, dict) and _as_text(item.get("question"))]
    if valid_mcqs:
        _heading(document, "Practice MCQs")
        for index, item in enumerate(valid_mcqs, 1):
            q_paragraph = document.add_paragraph()
            q_run = q_paragraph.add_run(f"{index}. {_as_text(item.get('question'))}")
            q_run.bold = True
            q_run.font.size = Pt(11)
            q_run.font.color.rgb = INK
            for option in _as_list(item.get("options")):
                option_paragraph = document.add_paragraph(style="List Bullet")
                option_run = option_paragraph.add_run(option)
                option_run.font.size = Pt(10)
                option_run.font.color.rgb = INK
            answer = _as_text(item.get("correct_answer"))
            if answer:
                _body(document, f"Correct answer: {answer}", color=BRAND_BLUE, size=10)
            explanation = _as_text(item.get("explanation"))
            if explanation:
                _body(document, f"Why: {explanation}", color=MUTED, size=10)

    # Glossary
    glossary = content.get("glossary") or []
    glossary_pairs = [
        (_as_text(item.get("term")), _as_text(item.get("meaning")))
        for item in glossary
        if isinstance(item, dict) and _as_text(item.get("term"))
    ]
    if glossary_pairs:
        _heading(document, "Glossary")
        for term, meaning in glossary_pairs:
            paragraph = document.add_paragraph(style="List Bullet")
            term_run = paragraph.add_run(f"{term}: ")
            term_run.bold = True
            term_run.font.size = Pt(11)
            meaning_run = paragraph.add_run(meaning)
            meaning_run.font.size = Pt(11)

    # Study checklist
    checklist = _as_list(content.get("study_checklist"))
    if checklist:
        _heading(document, "Study Checklist")
        for item in checklist:
            paragraph = document.add_paragraph()
            run = paragraph.add_run(f"☐  {item}")
            run.font.size = Pt(11)
            run.font.color.rgb = INK

    buffer = io.BytesIO()
    document.save(buffer)
    buffer.seek(0)
    return buffer


def safe_filename(title):
    base = _as_text(title) or "studypilot-notes"
    base = "".join(char if char.isalnum() or char in " -_" else "" for char in base).strip()
    base = base.replace(" ", "-").lower()[:60] or "studypilot-notes"
    return f"{base}.docx"
