# Generated by Django 6.0.5 on 2026-08-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='subtopic',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
