# Generated by Django 5.2.14 on 2026-05-14 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('resource_type', models.CharField(choices=[('youtube', 'YouTube'), ('textbook', 'Textbook'), ('pdf', 'PDF'), ('article', 'Article'), ('link', 'Link')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('course_title', models.CharField(blank=True, max_length=180)),
                ('is_saved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
