# Generated by Django 5.2.14 on 2026-05-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedresource',
            name='author_or_channel',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='savedresource',
            name='published_date',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='savedresource',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='savedresource',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
