# Generated by Django 5.2.14 on 2026-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcarddeck',
            name='course_title',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
