// The browser now reads PDFs that PyMuPDF used to read on the server. This runs
// the frontend's reader over a real PDF and checks it against what the Django
// backend produced for the same file (see test/pdf-expected.json, generated by
// apps/documents/services.extract_pdf_text).

import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
// @ts-expect-error - plain JS module shared with the frontend build
import { calculateFocusRange, readPdf } from "../../studypilot/src/lib/pdfText.js";
import expected from "./pdf-expected.json";

const pdfPath = fileURLToPath(new URL("./sample-lecture.pdf", import.meta.url));

// In a browser the worker comes from the bundler as a URL. Under Node it has to
// be the file on disk, so it is set before the reader loads pdf.js.
// pdfjs-dist is a frontend dependency, so it is resolved from there.
const pdfjs = await import("../../studypilot/node_modules/pdfjs-dist/legacy/build/pdf.mjs");
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  "../../studypilot/node_modules/pdfjs-dist/legacy/build/pdf.worker.min.mjs",
  import.meta.url,
).href;

describe("in-browser PDF reading", () => {
  it("matches PyMuPDF's focus range arithmetic", () => {
    expect(calculateFocusRange(12)).toEqual([4, 9]);
    expect(calculateFocusRange(3)).toEqual([0, 3]);
    expect(calculateFocusRange(0)).toEqual([0, 0]);
    expect(calculateFocusRange(1)).toEqual([0, 1]);
  });

  it("extracts the same document the Django backend did", async () => {
    const bytes = await readFile(pdfPath);
    const file = { arrayBuffer: async () => bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) };
    const result = await readPdf(file);

    expect(result.page_count).toBe(expected.page_count);
    expect(result.focused_start_page).toBe(expected.focused_start_page);
    expect(result.focused_end_page).toBe(expected.focused_end_page);
    // pdf.js and PyMuPDF lay out whitespace slightly differently, so the text
    // is compared by content and size rather than byte for byte.
    expect(result.text.slice(0, 60)).toBe(expected.text_head.slice(0, 60));
    expect(result.text.length).toBeGreaterThan(expected.text_len * 0.9);
    expect(result.text.length).toBeLessThan(expected.text_len * 1.1);
    expect(result.focused_text.length).toBeGreaterThan(expected.focused_len * 0.9);
    // The study context the Worker will generate from is picked here too.
    expect(result.study_context.length).toBeGreaterThan(expected.context_len * 0.9);
    expect(result.study_context_retry.length).toBeGreaterThan(1000);
    expect(result.study_context).not.toBe(result.study_context_retry);
  });
});
